### PR TITLE
Store a list of modules installed using modman

### PR DESCRIPTION
**Pull request by mwgamble**
After applying this commit, modules will be added and removed from a
newly-created .repos file inside the .modman directory. This file is
intended to be committed to the super-repository, and is roughly
equivalent to the lock file in Composer.

This is only really relevant if you're working on a site from more than
one location, which is often the case when you're working in a
multi-user environment.

### CODE REVIEW

**Comment by cobhimself** [comment]
Any progress being made on this? I'd patch it myself but I'm no bash wizard.

**Comment by hmphu** [comment]
@mwgamble Any progress on this request? It is really needed in Modman

**Comment by mwgamble** [comment]
We don't use modman now, and we'd recommend against using it. [Composer](https://getcomposer.org), plus the [Magento Composer Installer](https://packagist.org/packages/magento-hackathon/magento-composer-installer), is a much better solution.

**Comment by colinmollenhour** [comment]
@mwgamble Different tools for different needs, but I'm glad you've found happiness.  ;-)

**Pull request closed without merging**
