### PR TITLE
#81 --quiet: prevent output of non-interactive commands

### PR DESCRIPTION
**Pull request by possi**
https://github.com/colinmollenhour/modman/issues/81

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Thanks for the PR, @possi. However, I am a little uncertain about merging this currently. Reasons being:

1. Conventionally, the suppressable output (non-errors) should be output to `stdout` and the errors should be output to `stderr`. This way one can simply use `> /dev/null` to get rid of the non-error output.
2. The feature is incomplete. If the `--quiet` option exists it should be implemented for all commands, not just repair and clean.

I think ideally the verbose output should be on stdout and warnings and errors on stderr. Then, the `--quiet` option would be used to suppress verbose output and warnings but not errors. So the options would be:

* modman command (all output)
* modman command > /dev/null (only warnings and errors)
* modman command --quiet (only errors)
* modman command > /dev/null 2>&1 (nothing)

**Comment by possi** [comment]
I agree that the implementation is incomplete and could be optimized.

But I don't think that you should use stderr for warnings. In my opinion only errors (which causes the the return code to be != 0) should be send to stderr. It is usual, that you can use a --quiet option to suppress all the default output, e.g. if you like to use it in a cronjob.

* modman command (all output)
* modman command --quiet (only warnings and errors)
* modman command >/dev/null (only errors)
* modman command --quiet 2>/dev/null (only warnings, even if there is absolute no usecase for that)
* and like always: modman command > /dev/null 2>&1 (nothing)


Explanation of my use case:
I'm having more than 10 modules, with each 5 or more links in it. Some of them 3rd-Party, some of them self-written. When I change any of the modules modman-file I need to repair. Executing "modman repair" gives more than one page of output (my terminal usual shows 48 lines). 
That way I don't see if there's is something wrong, like typo in modman-file or such. Using "modman repair >/dev/null" in that case, gives the feeling of suppressing to much.

PS. An alternative would be, to not output all "Applied"-Lines if there is no -v|--verbose-Option.

**Comment by colinmollenhour** [comment]
Ok, I will concede that warnings could go to stdout if you prefer. I am against adding a verbose option to get the current behavior, though.

Is it really necessary to use "repair"? I can't even remember the last time I actually *needed* to use this. I think since the time it was added there have been improvements so that the only time it should be needed is if a line is completely removed from the modman file but the file it points to is not, and the symlink that is left over is able to break something by being there unintentionally.

**Comment by possi** [comment]
Updated --quiet to affect more commands.

About using repair: For product I usually use deploy-all, but while creating new modules, or updateting them I prefer repair --quiet to check if every of our dozen submodules are configured correctly.

Also sometime it happens that we have to change ```directory```-Symlink to ```directory/*``` what only can be done correctly using repair.

**Comment by Igloczek** [comment]
@colinmollenhour could you merge this or there are some other things that prevent adding this super useful feature?

**Comment by colinmollenhour** [comment]
Merged.

**Comment by Igloczek** [comment]
Thanks! ❤️

**Comment by Igloczek** [comment]
@colinmollenhour sorry for interrupting you once again, but is there a chance to do a release with the merged code? There are quite few changes in the master branch since v1.12.

I know that the official installation way does not require it, but there are other ways, like homebrew, which require versioning, to work properly.

**Comment by colinmollenhour** [comment]
Sure, 1.13 tagged.

**Pull request merged**
